### ISSUE TITLE
Избежать создания картинки в JS посредством CSS

### ISSUE THREAD

**Issue by Kerminator1973** [Kerminator1973/WebDevelopment#2]
Было:

``` js
let icon = document.createElement('img');
icon.src = "../images/minus24.png";

let removeLink = document.createElement('span');
removeLink.className = "svgtool";
removeLink.onclick = function() {removeFromFavorite(model, compressedModel);};
removeLink.appendChild(icon);
deco.appendChild(removeLink);
```

Стало:

``` js
let removeLink = document.createElement('span');
removeLink.className = "svgtool";
removeLink.onclick = function() {removeFromFavorite(model, compressedModel);};
deco.appendChild(removeLink);
```

``` css
.favmodel>span.svgtool {
	background: url(../images/minus24.png) center center no-repeat;
	background-size: contain;
	max-width: 20%;
	position: absolute;
	right: 0;
}
```
