### ISSUE TITLE
Отладка docker-compose.yaml

### ISSUE THREAD

**Issue by Kerminator1973** [Kerminator1973/WebDevelopment#5]
Базовый скрипт вот такой:

```yaml
name: ProIDC3

services:
  db:
    image: cinna-postgres
    environment:
      POSTGRES_DB: proidc3
      POSTGRES_PASSWORD_FILE: /run/secrets/db_pswd
    secrets:
      - db_pswd
  app:
    image: cinna-pages
    ports:
      - "8070:8080"

secrets:
   db_pswd:
     file: db_pswd.txt
```
